### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' (smtp_sen_email)

### ISSUE THREAD

**Issue by ssemenukha** [sendpulse/sendpulse-rest-api-python#7]
While running sendpulse-rest-api-example.py got an error

INFO     [2018-08-21 10:51:01,895]  Function call: smtp_send_mail
Traceback (most recent call last):
  File "sendpulse-rest-api-example.py", line 111, in <module>
    SPApiProxy.smtp_send_mail(email)
  File "/home/...../pysendpulse.py", line 639, in smtp_send_mail
    email['html'] = base64.b64encode(email.get('html'))
  File "/usr/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

**Comment by sendpulse** [comment]
Thank you. Fixed into master.

**Comment by vtonse** [comment]
Thanks for the solution
